[package]
name = "atlas-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
poise = "0.6.1"
shuttle-runtime = "0.47.0"
shuttle-serenity = "0.47.0"
sqlite = "0.36.1"
tokio = "1.40.0"
